### ISSUE TITLE
Error to run the script to format the db for diamond

### ISSUE THREAD

**Issue by llk578496** [EBI-Metagenomics/mobilome-annotation-pipeline#22]
Hi, thank you for developing this pipeline. We are particularly interested in the MGE and AMR annotation part, as they help uncover the associations between them. However, when we attempted to run the script to format the mobileOG-database for diamond, we encountered the following error:

> (mobilome-annotation-pipeline) gilman_siu2@gilmansiu2-Z490-VISION-D:/mnt/data6/TEST/mobilome-annotation-pipeline/mobilome-annotation-pipeline/databases$ nextflow run /mnt/data6/TEST/mobilome-annotation-pipeline/mobilome-annotation-pipeline/format_mobileOG.nf
> N E X T F L O W  ~  version 23.10.1
> Launching `/mnt/data6/TEST/mobilome-annotation-pipeline/mobilome-annotation-pipeline/format_mobileOG.nf` [reverent_allen] DSL2 - revision: 40a4d181cc
> executor >  local (1)
> [66/31298b] process > database_format (1) [  0%] 0 of 1
> executor >  local (1)
> [66/31298b] process > database_format (1) [100%] 1 of 1, failed: 1 ✘
> ERROR ~ Error executing process > 'database_format (1)'
> 
> Caused by:
>   Process `database_format (1)` terminated with an error exit status (127)
> 
> Command executed:
> 
>   diamond makedb --in mobileOG-db_beatrix-1.6.All.faa --db mobileOG_beatrix1.6.dmnd
> 
> Command exit status:
>   127
> 
> Command output:
>   (empty)
> 
> Command error:
>   .command.sh: line 2: diamond: command not found
> 
> Work dir:
>   /mnt/data6/TEST/mobilome-annotation-pipeline/mobilome-annotation-pipeline/databases/work/66/31298bde9cca9193ef73c85fe47226
> 
> Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
> 
>  -- Check '.nextflow.log' file for details

May we know how should we solve this problem? Thank you very much.

Eddie

**Comment by Ales-ibt** [comment]
Hello Eddie, thank you for your interest in using the Mobilome Annotation Pipeline and sorry about the late reply. 

What is missing here is the location of the container in the config file. 

I have added the singularity enabled to the local config file so you can use `-profile local` on your command now. Please do a `git pull` before trying again.  

In addition, you will need to manually download and extract the [AMRFinder plus db](https://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/latest) and the [geNomad database](https://zenodo.org/records/8339387) databases. Then you can provide the paths to your databases using the `mobileog_db`, the `amrfinder_plus_db` and the `genomad_db` respectively when you run the pipeline. I will update the README file to include this information.

I hope you find this useful.

**Comment by lianmsu** [comment]
Hello, thank you so much for doing this work,  it greatly improves people's productivity and I have some questions for you.

How exactly do I manually download and extract the AMRFinder plus db and the geNomad database databases. geNomad databases have HMMER HMM models and FASTA format. not sure. Which one do I need to download here.
After downloading and extracting the databases, do I need to do the same as for the mobileOG databases?

Looking forward to your reply.
Best wishes, pengwei li

**Comment by Ales-ibt** [comment]
Hello Pengwei,

This is what you need to do to download and format the databases:

AMRfinder:
The files you need to run AMRfinder can be downloaded recursively using wget, but I can see they need to be formatted for blast. I didn't do it by myself, @tgurbich, can you please tell us how did you format the AMRFinder databases?

geNomad:
   From their [zenodo](https://zenodo.org/records/8339387) site, you can click on download all, decompress and put the files under the same directory. Then you can pass the path to the pipeline using the `genomad_db ` flag.

mobileOG:
  From their [website](https://mobileogdb.flsi.cloud.vt.edu/entries/database_download) select 'Download all data' and do:
```bash
$ mv beatrix-1-6_v1_all.zip /PATH/mobilome-annotation-pipeline/databases
$ cd /PATH/mobilome-annotation-pipeline/databases
$ unzip beatrix-1-6_v1_all.zip
$ nextflow run /PATH/mobilome-annotation-pipeline/format_mobileOG.nf
```

**Comment by tgurbich** [comment]
Hi,

You need to index the AMRfinderPlus db and you can use the AMRfinderPlus container to use their indexing algorithm. Here is an example of how this can be done:

```
wget -r -nH --cut-dirs=5 \\
    ftp://ftp.ncbi.nlm.nih.gov/pathogen/Antimicrobial_resistance/AMRFinderPlus/database/3.12/2024-01-31.1/

    amrfinder_index 2024-01-31.1

```
You can also run the `amrfinder --update` command which should download the latest db version and index it.

**Comment by lianmsu** [comment]
Thank you very much for your help, your eagerness to help has helped me a lot. Appreciate it!

Also, I noticed that ICEfinder is currently updated to version 2, but the download instriction for this pipline mentions ICEfinder version 1. The developers of ICEfinder are currently offering version 2, does this affect usage, or is it still the original download method? 

Or is it possible to provide an updated installation of ICEfinder v2.

Thank you very much for your help! Best wishes!

**Comment by Ales-ibt** [comment]
Hello! Thank you for letting us know about ICEfinder v2. I've sent an email to request the new version of the tool to the author but I haven't heard from him. As soon as I get the tarball and test the tool, I will update the instructions if we find the update convenient.

Bests

**Comment by mberacochea** [comment]
I'm closing this one. For the ICEFinder v2, we have a ticket on our backlog.
