### ISSUE TITLE
  Process `GENOMAD (1)` terminated with an error exit status (2)

### ISSUE THREAD

**Issue by Andrewab9** [EBI-Metagenomics/mobilome-annotation-pipeline#35]
Hi everyone!
I encountered this error:
ERROR ~ Error executing process > 'GENOMAD (1)'

Caused by:
  Process `GENOMAD (1)` terminated with an error exit status (2)

Command executed:

  genomad end-to-end         --threads 1         5kb_contigs.fasta         genomad_out         /mnt/hdd3/andre/tools/mobilome-annotation-pipeline/genomad_db

This was the command i ran:

nextflow run ebi-metagenomics/mobilome-annotation-pipeline -r v2.0.1 --assembly ../17A_pilon.fasta --user_genes true --prot_gff metannotator_results/17A/functional_annotation/merged_gff/17A_annotations.gff --virify true --vir_gff results_virify/17A_pilon/08-final/gff/17A_pilon_virify.gff --vir_checkv results_virify/17A_pilon/07-checkv/\*quality_summary.tsv --outdir mobilome_results --skip_crispr true --skip_amr true -profile docker --genomad_db /mnt/hdd3/andre/tools/mobilome-annotation-pipeline/genomad_db

It seems that it doesn't recognize the db, so i tried to install genomad locally and run it on the db that i've manually downloaded and extracted, and it works. 
Thank you for making all these great tools and for the help

**Comment by mberacochea** [comment]
Hi @Andrewab9,

Apologies for the delay in our response. If you still have the .nextflow.log file could you please attach it to the ticket?.

Cheers

**Comment by Andrewab9** [comment]
> Hi @Andrewab9,
> 
> Apologies for the delay in our response. If you still have the .nextflow.log file could you please attach it to the ticket?.
> 
> Cheers

Hi mberacochea, thank you for your reply.
I've managed to modify some of the files to run genomad but this time it gives me the following error:
ERROR ~ Error executing process > 'DIAMOND (1)'

Caused by:
  Path value cannot be empty



Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details

[.nextflow.log](https://github.com/user-attachments/files/16839055/default.nextflow.log)

Attached you can find the log.

This is the command i ran: nextflow run main.nf --assembly ../../s_aureus/fasta_pilon_2_run/17A_pilon.fasta --user_genes true --prot_gff /mnt/hdd3/andre/s_aureus/fasta_pilon_2_run/metannotator/metannotator_results/17A/functional_annotation/merged_gff/17A_annotations.gff --virify true --vir_gff ../../s_aureus/fasta_pilon_2_run/metannotator/results_virify/17A_pilon/08-final/gff/17A_pilon_virify.gff --vir_checkv ../../s_aureus/fasta_pilon_2_run/metannotator/results_virify/17A_pilon/07-checkv/\*quality_summary.tsv --outdir ../../s_aureus/fasta_pilon_2_run/metannotator/17A_mobilome_2 --skip_crispr true --skip_amr true -profile docker --icefinder_sif singularity/icefinder-v1.0-local.sif

**Comment by Andrewab9** [comment]
> Hi @Andrewab9,
> 
> Apologies for the delay in our response. If you still have the .nextflow.log file could you please attach it to the ticket?.
> 
> Cheers

Hi @mberacochea, thank you for your reply.
I've managed to modify some of the files to run genomad but this time it gives me the following error:
ERROR ~ Error executing process > 'DIAMOND (1)'

Caused by:
  Path value cannot be empty



Tip: you can try to figure out what's wrong by changing to the process work dir and showing the script file named `.command.sh`

 -- Check '.nextflow.log' file for details

[.nextflow.log](https://github.com/user-attachments/files/16839123/default.nextflow.log)

Attached you can find the log.

This is the command i ran: nextflow run main.nf --assembly ../../s_aureus/fasta_pilon_2_run/17A_pilon.fasta --user_genes true --prot_gff /mnt/hdd3/andre/s_aureus/fasta_pilon_2_run/metannotator/metannotator_results/17A/functional_annotation/merged_gff/17A_annotations.gff --virify true --vir_gff ../../s_aureus/fasta_pilon_2_run/metannotator/results_virify/17A_pilon/08-final/gff/17A_pilon_virify.gff --vir_checkv ../../s_aureus/fasta_pilon_2_run/metannotator/results_virify/17A_pilon/07-checkv/\*quality_summary.tsv --outdir ../../s_aureus/fasta_pilon_2_run/metannotator/17A_mobilome_2 --skip_crispr true --skip_amr true -profile docker --icefinder_sif singularity/icefinder-v1.0-local.sif

**Comment by mberacochea** [comment]
You are missing one parameter, `mobileog_db` which should be downloaded and formatted -> https://github.com/EBI-Metagenomics/mobilome-annotation-pipeline?tab=readme-ov-file#install-and-dependencies
