### ISSUE TITLE
Problems with icefinder.pl

### ISSUE THREAD

**Issue by Leytoncito** [EBI-Metagenomics/mobilome-annotation-pipeline#41]
Dear team,

Thank you very much for developing such a useful tool. I have been trying to run it, and although I had no prior experience with Singularity or Nextflow, I managed to resolve most of the issues I encountered along the way. However, I’m now facing a final error (attached at the end of this message) that I cannot seem to understand.

As far as I can see, it appears to be looking for Perl files in a local directory. I created the `.sif` file using ICEfinder version 2, provided by the author, though I’m unsure if this version might be causing the issue or if there’s a specific adjustment needed in the` icefinder.nf `configuration file for my setup.

Below, I’ve included the command and the error message for further context:

COMANDO
`nextflow run -profile local ~/shared/softwares/mobilome-annotation-pipeline/main.nf --assembly T1_assembly_final.contigs.fa --icefinder_sif ~/shared/softwares/mobilome-annotation-pipeline/templates/icefinder-v1.0-local.sif --singularity_cachedir ./cashe_dir -resume`

ERROR
```
[2d/377a4a] NOTE: Process `ICEFINDER (1)` terminated with an error exit status (2) -- Execution is retried (3)
ERROR ~ Error executing process > 'ICEFINDER (1)'

Caused by:
  Process `ICEFINDER (1)` terminated with an error exit status (2)


Command executed:

  cd /install/ICEfinder_linux/ && perl ./ICEfinder_local.pl input.list

  if ls -ld result/contig* 2>/dev/null | grep -q .
  then
      cat result/*/*summary.txt > result/icf_concat.summary
      grep 'DR:' result/*/ICE* > result/icf_dr.txt
  else
      echo 'ICEfinder found 0 ICE/IME in assembly... generating dummy files'
      touch result/icf_concat.summary
      touch result/icf_dr.txt
  fi

Command exit status:
  2

Command output:
  (empty)

Command error:
  Can't open perl script "./ICEfinder_local.pl": No such file or directory

Work dir:
  /home/unigenbio/leytoncito/tmp_metagenomes/work/03/7b617e4891b5efac75c25ddda3d2e6

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line
```

Thanks in advance
Benjamin leyton
[.nextflow.log](https://github.com/user-attachments/files/17557346/default.nextflow.log)

**Comment by mberacochea** [comment]
Hey @Leytoncito 

ICEFinder is a very awkward tool, can you run the following commands to see what's in your singularity image plase:

```bash
$ singularity run icefinder-v1.0-local.sif bash
Singularity> ls /install/ICEfinder_linux/
ICEfinder.log  ICEfinder_local.pl  LICENSE_ICEfinder1.txt  README.txt  data  example  gbk  input.list  result  scripts	tmp  tools
Singularity> cd /install/ICEfinder_linux/
Singularity> perl ./ICEfinder_local.pl

Welcome to use ICEfinder local version!
ICEfinder is a perl-based tool to predicte the ICE.
-------------------------------------------------------------------------------------------------
Usage:	perl ICEfinder_local.pl list_file

The list file should contain the names of GenBank files(*.gbk or *.gb)in the directory 'IMEfinder/gbk' line by line.
List File Format Example
=====
AL009126.gbk
BA000037.gbk
HS11286.gbk
NC_003888.gbk


For more details, please see the README.txt file.

If you have any question, please feel free to contact the authors:
hyou@sjtu.edu.cn
liumeng94@sjtu.edu.cn

```

Where `icefinder-v1.0-local.sif ` is the name of the image you built

Cheers

**Comment by Leytoncito** [comment]
Hi @mberacochea,

Thank you for your response; it has been very enlightening for me. The` icefinder-v1.0-local.sif ` image is located in the templates folder.

I followed the commands as you suggested, and it seems the issue is not with the Singularity image itself. The problem is that I built an image with ICEFinder 2 instead of ICEFinder 1.

```
Singularity> cd /install/ICEfinder2_linux/
Singularity> ls
ICEfinder2.py  LICENSE  README.txt  config.ini  data  example  result  script  tmp  tool  tools
```
This version is written in Python, which takes a different approach. Therefore, I will kindly request version 1 from the author. I actually asked for version 1, but the author provided version 2.

I will keep you updated if any issues with ICEFinder persist.

Thanks again for your help!

**Comment by mberacochea** [comment]
Hey @Leytoncito,

That makes sense. ICEFinder is a tricky one since the source isn't easily accessible. Early next year, we will look into upgrading ICEFinder, but we don't have the capacity at the moment.

I'll close this ticket. Please create another issue if you encounter any more problems.

Cheers
